// Schools Variable
const PhiH_Schools = {
    "schools": [
        {
            "id": "school1",
            "ar": {
                "name": "التنوير",
                "first_letter": "ت",
                "name_and_origin": "التنوير، اصطلاحا، دال على الإضاءة في مقابل الظلمة أو العتمة، أمّا فلسفيًا فهو دال على ما يُشِعُهُ العقل من حوله من نور ومعرفة وهو حركة فلسفية (Enlightenment) (Les lumières) انتشرت في أوروبا في القرن الثامن عشر بانقلترا مع \"لوك\" و\"هيوم\" و\"نيوتن\"، وبفرنسا مع \"منتسكيو\" و\"روسو\" و\"فولتير\" و\"ديدرو\" و\"المبار\" ... وعبّر عنها وولف وليسنغ وكانط. وتمتدّ بعض جذور هذه الحركة في الحضارة اليونانية والحضارة العربية الإسلامية إذ نجد في كليهما تأكيدا على فعالية العقل التحرّرية والتنويرية (أفلاطون، ابن رشد ...).",
                "pioneers_and_reference_texts": "لوك، هيوم، نيوتن، منتسكيو، روسو، فولتير، ديدرو، المبار، وولف، ليسنغ، كانط. من النصوص المرجعية: \"مقال في الفهم البشري\" (لوك)، \"مقال في التسامح\" (فولتير)، \"العقد الاجتماعي\" (روسو)، \"روح القوانين\" (منتسكيو)، \"ما هي الأنوار؟\" (كانط).",
                "central_thesis_and_key_concepts": "تقوم حركة التنوير على مبدأ نظري مفاده أن أنوار العقل الطبيعية هي الوحيدة القادرة على قيادة البشر نحو تطوير المعارف والعلوم في سياق تصوّر للتاريخ يقوم على نموذج التقدّم. فأعطت للعقل أولوية على النقل وأعلنت بذلك عن تحرّرها من الفكر الكنسي.",
                "method_and_domain": "استخدام العقل والنقد في جميع المجالات: الفلسفة، السياسة، الأخلاق، الدين، العلم. الاعتماد على المنهج التجريبي والعقلاني معًا.",
                "relations_and_critique": "علاقة قطع مع الفكر الكنسي والتقليدي، نقد السلطة الدينية والسياسية المطلقة. تعرضت لانتقادات من التيارات الرومانسية والمحافظة التي رأت في العقلانية التنويرية تجريدًا وإغفالًا للجانب العاطفي والتاريخي.",
                "impact_and_applications": "عبّرت هذه الحركة عن طموحات الطبقة البرجوازية الصاعدة سواء في المجال التجاري أو الصناعي برفعها من شأن قيمتي الحرية والمساواة وهيأت إيديولوجيًّا للقطع مع المَلَكيّة والاقطاعية. تجسّدت في المستوى السياسي عبر رسم محدودية سلطة الدولة من خلال الفصل بين السلطات وتأكيد أفضلية النظام الديمقراطي.",
                "equivalent_terms": "عصر الأنوار، حركة التنوير، فلسفة الأنوار",
                "other": "\"إنّ بلوغ الأنوار هو خروج الإنسان من القصور الذي هو مسؤول عنه والذي يعني عجزه عن استعمال عقله دون إرشاد الغير ... تجرّأ على أن تعرف ! كن جريئا في استعمال عقلك أنت ! ذاك شعار الأنوار.\" - كانط"
            },
            "fr": {
                "name": "Lumières",
                "first_letter": "L",
                "name_and_origin": "Les Lumières, terme désignant l'éclairage par opposition à l'obscurité ou aux ténèbres, philosophiquement, il désigne la lumière et la connaissance que la raison diffuse autour d'elle. C'est un mouvement philosophique (Enlightenment) qui s'est répandu en Europe au XVIIIe siècle en Angleterre avec \"Locke\", \"Hume\" et \"Newton\", et en France avec \"Montesquieu\", \"Rousseau\", \"Voltaire\", \"Diderot\", \"d'Alembert\" ... et exprimé par Wolff, Lessing et Kant. Certaines racines de ce mouvement s'étendent dans la civilisation grecque et la civilisation arabo-islamique où nous trouvons dans les deux une affirmation de l'efficacité libératrice et éclairante de la raison (Platon, Averroès ...).",
                "pioneers_and_reference_texts": "Locke, Hume, Newton, Montesquieu, Rousseau, Voltaire, Diderot, d'Alembert, Wolff, Lessing, Kant. Textes de référence : \"Essai sur l'entendement humain\" (Locke), \"Traité sur la tolérance\" (Voltaire), \"Du contrat social\" (Rousseau), \"De l'esprit des lois\" (Montesquieu), \"Qu'est-ce que les Lumières ?\" (Kant).",
                "central_thesis_and_key_concepts": "Le mouvement des Lumières repose sur un principe théorique selon lequel les lumières naturelles de la raison sont les seules capables de conduire l'humanité vers le développement des connaissances et des sciences dans un contexte de conception de l'histoire basée sur le modèle du progrès. Il a donné la priorité à la raison sur la tradition et a ainsi annoncé sa libération de la pensée ecclésiastique.",
                "method_and_domain": "Utilisation de la raison et de la critique dans tous les domaines : philosophie, politique, éthique, religion, science. Recours à la méthode empirique et rationnelle à la fois.",
                "relations_and_critique": "Relation de rupture avec la pensée ecclésiastique et traditionnelle, critique de l'autorité religieuse et politique absolue. A été critiquée par les courants romantiques et conservateurs qui voyaient dans le rationalisme des Lumières une abstraction et une négligence de l'aspect émotionnel et historique.",
                "impact_and_applications": "Ce mouvement a exprimé les aspirations de la bourgeoisie montante dans les domaines commercial et industriel en élevant les valeurs de liberté et d'égalité et a préparé idéologiquement la rupture avec la monarchie et la féodalité. Il s'est incarné au niveau politique en dessinant la limitation du pouvoir de l'État à travers la séparation des pouvoirs et en affirmant la supériorité du système démocratique.",
                "equivalent_terms": "Siècle des Lumières, mouvement des Lumières, philosophie des Lumières",
                "other": "\"Les Lumières se définissent comme la sortie de l'homme hors de l'état de minorité dont il est lui-même responsable. La minorité est l'incapacité de se servir de son entendement sans la direction d'autrui. Aie le courage de te servir de ton propre entendement ! Voilà la devise des Lumières.\" - Kant"
            },
            "en": {
                "name": "Enlightenment",
                "first_letter": "E",
                "name_and_origin": "The Enlightenment, terminologically, denotes illumination as opposed to darkness or obscurity, while philosophically it denotes the light and knowledge that reason radiates around itself. It is a philosophical movement that spread in Europe in the 18th century in England with \"Locke\", \"Hume\" and \"Newton\", and in France with \"Montesquieu\", \"Rousseau\", \"Voltaire\", \"Diderot\", \"d'Alembert\" ... and expressed by Wolff, Lessing and Kant. Some roots of this movement extend into Greek civilization and Arab-Islamic civilization where we find in both an affirmation of the liberating and enlightening effectiveness of reason (Plato, Averroes ...).",
                "pioneers_and_reference_texts": "Locke, Hume, Newton, Montesquieu, Rousseau, Voltaire, Diderot, d'Alembert, Wolff, Lessing, Kant. Reference texts: \"An Essay Concerning Human Understanding\" (Locke), \"A Treatise on Toleration\" (Voltaire), \"The Social Contract\" (Rousseau), \"The Spirit of the Laws\" (Montesquieu), \"What is Enlightenment?\" (Kant).",
                "central_thesis_and_key_concepts": "The Enlightenment movement is based on a theoretical principle that the natural lights of reason are the only ones capable of leading humanity towards the development of knowledge and sciences in the context of a conception of history based on the model of progress. It gave priority to reason over tradition and thus declared its liberation from ecclesiastical thought.",
                "method_and_domain": "Use of reason and criticism in all fields: philosophy, politics, ethics, religion, science. Reliance on both empirical and rational methods.",
                "relations_and_critique": "Relationship of rupture with ecclesiastical and traditional thought, critique of absolute religious and political authority. It was criticized by romantic and conservative currents who saw in Enlightenment rationalism an abstraction and a neglect of the emotional and historical aspect.",
                "impact_and_applications": "This movement expressed the aspirations of the rising bourgeoisie in the commercial and industrial fields by elevating the values of freedom and equality and thus prepared ideologically for the break with monarchy and feudalism. It was translated at the political level by drawing the limits of state power through the separation of powers and affirming the superiority of the democratic system.",
                "equivalent_terms": "Age of Enlightenment, Enlightenment movement, Enlightenment philosophy",
                "other": "\"Enlightenment is man's emergence from his self-incurred immaturity. Immaturity is the inability to use one's own understanding without the guidance of another. Have courage to use your own understanding! That is the motto of enlightenment.\" - Kant"
            }
        },
        {
            "id": "school2",
            "ar": {
                "name": "مدرسة فرانكفورت",
                "first_letter": "ف",
                "name_and_origin": "تسمية لمجموعة من الباحثين الألمان في الفلسفة وعلم الاجتماع الذين عقدوا لقاء تأسيسيًا سنة 1923 بمعهد الأبحاث الاجتماعية الذي أسّسه ماكس هوركهايمر بمدينة فرانكفورت.",
                "pioneers_and_reference_texts": "ماكس هوركهايمر، ثيودور أدورنو، هربرت ماركوزه، إريش فروم، يورغن هابرماس. من النصوص المرجعية: \"جدلية العقل\" (هوركهايمر وأدورنو)، \"الإنسان ذو البعد الواحد\" (ماركوزه)، \"النظرية التقليدية والنظرية النقدية\" (هوركهايمر)، \"الجدلية السالبة\" (أدورنو)، \"العلم والتقنية كإيديولوجيا\" (هابرماس).",
                "central_thesis_and_key_concepts": "بلورة \"النظرية النقدية\" التي تنقد المجتمع الرأسمالي المتقدّم وعلم الاجتماع وعلم النفس. مفاهيم رئيسية: العقل الأداتي، الصناعة الثقافية، المجتمع ذو البعد الواحد، الثورة الشاملة.",
                "method_and_domain": "نهج متعدد التخصصات يجمع بين الفلسفة وعلم الاجتماع والتحليل النفسي والنقد الثقافي. التركيز على النقد الجذري للمجتمع الرأسمالي المعاصر.",
                "relations_and_critique": "تأثرت بالفكر الماركسي والتحليل النفسي. انتقدت العقلانية كما تشتغل في المجتمعات الرأسمالية المعاصرة بما هي عقلانية محكومة بمنطق الأداء والنجاعة، وبما هي عقلانية عنيفة واستبدادية.",
                "impact_and_applications": "عمل أعضاء هذه المدرسة على التفكير في الأسباب التي أدّت إلى فشل الحركة العمالية في ألمانيا وفهم الأسباب التي أدّت بالنظام السوفياتي إلى البيروقراطية. دعوا إلى ثورة شاملة تعيد تصحيح توجّهات الحضارة اقتصاديّا واجتماعيًا وسياسيًا وثقافيًا.",
                "equivalent_terms": "مدرسة فرانكفورت النقدية، النظرية النقدية",
                "other": "انتهى هؤلاء إلى صياغة نظرة متشائمة حول التاريخ مختلفة عن النظرة المتفائلة التي رسمتها حركة الأنوار. كلّ مؤلفات المدرسة تمثّل مساءلة نقدية للعقلانية في المجتمعات الرأسمالية المعاصرة."
            },
            "fr": {
                "name": "École de Francfort",
                "first_letter": "F",
                "name_and_origin": "Désignation d'un groupe de chercheurs allemands en philosophie et sociologie qui ont tenu une réunion fondatrice en 1923 à l'Institut de recherche sociale fondé par Max Horkheimer dans la ville de Francfort.",
                "pioneers_and_reference_texts": "Max Horkheimer, Theodor Adorno, Herbert Marcuse, Erich Fromm, Jürgen Habermas. Textes de référence : \"La Dialectique de la raison\" (Horkheimer et Adorno), \"L'Homme unidimensionnel\" (Marcuse), \"Théorie traditionnelle et théorie critique\" (Horkheimer), \"Dialectique négative\" (Adorno), \"La Technique et la science comme 'idéologie'\" (Habermas).",
                "central_thesis_and_key_concepts": "Élaboration de la \"théorie critique\" qui critique la société capitaliste avancée, la sociologie et la psychologie. Concepts clés : raison instrumentale, industrie culturelle, société unidimensionnelle, révolution totale.",
                "method_and_domain": "Approche interdisciplinaire combinant philosophie, sociologie, psychanalyse et critique culturelle. Accent mis sur la critique radicale de la société capitaliste contemporaine.",
                "relations_and_critique": "Influencée par la pensée marxiste et la psychanalyse. A critiqué la rationalité telle qu'elle fonctionne dans les sociétés capitalistes contemporaines en tant que rationalité gouvernée par la logique de performance et d'efficacité, et en tant que rationalité violente et autoritaire.",
                "impact_and_applications": "Les membres de cette école ont réfléchi aux causes de l'échec du mouvement ouvrier en Allemagne et aux raisons qui ont conduit le système soviétique à la bureaucratie. Ils ont appelé à une révolution totale pour corriger les orientations de la civilisation sur les plans économique, social, politique et culturel.",
                "equivalent_terms": "École de Francfort critique, Théorie critique",
                "other": "Ils ont abouti à une vision pessimiste de l'histoire différente de la vision optimiste dessinée par le mouvement des Lumières. Toutes les œuvres de l'école représentent un questionnement critique de la rationalité dans les sociétés capitalistes contemporaines."
            },
            "en": {
                "name": "Frankfurt School",
                "first_letter": "F",
                "name_and_origin": "Designation for a group of German researchers in philosophy and sociology who held a founding meeting in 1923 at the Institute for Social Research founded by Max Horkheimer in the city of Frankfurt.",
                "pioneers_and_reference_texts": "Max Horkheimer, Theodor Adorno, Herbert Marcuse, Erich Fromm, Jürgen Habermas. Reference texts: \"Dialectic of Enlightenment\" (Horkheimer and Adorno), \"One-Dimensional Man\" (Marcuse), \"Traditional and Critical Theory\" (Horkheimer), \"Negative Dialectics\" (Adorno), \"Technology and Science as 'Ideology'\" (Habermas).",
                "central_thesis_and_key_concepts": "Development of \"critical theory\" that critiques advanced capitalist society, sociology, and psychology. Key concepts: instrumental reason, culture industry, one-dimensional society, total revolution.",
                "method_and_domain": "Interdisciplinary approach combining philosophy, sociology, psychoanalysis, and cultural criticism. Focus on radical critique of contemporary capitalist society.",
                "relations_and_critique": "Influenced by Marxist thought and psychoanalysis. Criticized rationality as it operates in contemporary capitalist societies as rationality governed by the logic of performance and efficiency, and as violent and authoritarian rationality.",
                "impact_and_applications": "Members of this school reflected on the causes of the failure of the workers' movement in Germany and the reasons that led the Soviet system to bureaucracy. They called for a total revolution to correct the directions of civilization economically, socially, politically and culturally.",
                "equivalent_terms": "Frankfurt Critical School, Critical Theory",
                "other": "They ended up formulating a pessimistic view of history different from the optimistic view drawn by the Enlightenment movement. All the school's works represent a critical questioning of rationality in contemporary capitalist societies."
            }
        },
        {
            "id": "school3",
            "ar": {
                "name": "المنطق الرّواقي",
                "first_letter": "م",
                "name_and_origin": "هو منطق ذو أصول ميغارية، نشأ في المدرسة الرواقية الفلسفية. خلافاً لمنطق أرسطو الذي كان متناسباً مع فلسفة المادة والجوهر (منطق المفهوم)، يحيل المنطق الرواقي على فلسفة إسمانية (nominaliste) تعتبر أن لا وجود لأنواع ولا لجواهر بل فقط الكائنات ووقائع فرديّة.",
                "pioneers_and_reference_texts": "زينون القبرصي (264-335 ق.م) مؤسس المدرسة الرواقية، كريسيب (280-204 ق.م) الذي طور المنطق الرواقي بشكل منهجي. بسبب فقدان معظم النصوص الأصلية، فإن معرفتنا بالمنطق الرواقي تأتي من مصادر لاحقة مثل كتابات سيكستوس إمبيريكوس، وغالينوس، وكتابات بعض الفلاسفة المسيحيين.",
                "central_thesis_and_key_concepts": "القضايا المنطقية تعبر في نظرهم عن وقائع تحدث في الزمن أو عن روابط بين وقائع. يميّزون بين القضايا البسيطة والمركّبة، وتتوزّع القضايا المركّبة إلى ستة أصناف: 1) قضية شرطية 2) قضية متوالية أو إسنادية 3) قضية عطفيّة (أو منسّقة) 4) قضية فاصلة 5) قضية سببية 6) قضية تشبيهية (تصعيديّة وتخفيضيّة).",
                "method_and_domain": "يتألف الاستدلال من مقدمة كبرى ومقدمة صغرى ونتيجة. اعتمد الرواقيون الكناية في صياغة أشكال الاستدلال. قدّم كريسيب خمس طرق في تنظيم الاستدلال تعتمد على أشكال استدلالية محددة.",
                "relations_and_critique": "علاقة وثيقة بالمنطق الميغاري، وخلاف جذري مع المنطق الأرسطي في النظر إلى طبيعة القضايا والاستدلال. تعرض المنطق الرواقي لانتقادات من قبل المشّائين الذين فضلوا المنطق الأرسطي، لكنه أثّر لاحقاً على تطور المنطق القضيوي (الاقتراحي).",
                "impact_and_applications": "يُعتبر المنطق الرواقي أول صياغة منهجية للمنطق القضيوي (الاقتراحي) في تاريخ الفكر الغربي. شكّل جزءاً أساسياً من الفلسفة الرواقية إلى جانب الفيزياء والأخلاق. أثّر على تطور المنطق في العصور الوسطى وعلى بعض جوانب المنطق الحديث.",
                "equivalent_terms": "المنطق الرواقي، منطق الرواقيين، المنطق القضيوي الرواقي",
                "other": "يعتبر الرواقيّون أنه من الصواب يُستنتج الصواب ومن الخطأ يُستنتج الخطأ، وقد ينتج الصواب عن الخطأ لكن الخطأ لا يُستنتج من الصواب. الجدول التالي يوضح أصناف القضايا المركبة عند الرواقيين:\n\n<table>\n<tr><th colspan='2'>صنف القضيّة</th><th>مثال عليها</th></tr>\n<tr><td colspan='2'>قضية شرطية</td><td>إذا كان هناك نهار كان هناك نور</td></tr>\n<tr><td>قضية متوالية أو إسنادية</td><td>Proposition consécutive ou inférentielle</td><td>بما أن هناك نهارا فهناك نور</td></tr>\n<tr><td>قضية عطفيّة (أو منسّقة)</td><td>Proposition Conjonctive</td><td>هناك نهار وهناك نور</td></tr>\n<tr><td>قضية فاصلة</td><td>Proposition disjonctive</td><td>إمّا هناك نهار وإمّا هناك نور</td></tr>\n<tr><td>قضية سببية</td><td>Proposition Causale</td><td>لأنّ هناك نهارا هناك نور</td></tr>\n<tr><td colspan='2'>قضية تشبيهية تصعيديّة</td><td>هناك نهار أكثر مما هناك ليل</td></tr>\n<tr><td colspan='2'>قضية تشبيهية تخفيضيّة</td><td>هناك ليل أقلّ ممّا هناك نهار</td></tr>\n</table>\n\nوإليك أشكال الاستدلال الخمسة عند كريسيب:\n\n<table>\n<tr><th>شكل الاستدلال</th><th>مثال عليه</th></tr>\n<tr><td>إذا الأوّل الثاني، بما أنّ الأوّل، إذن الثاني</td><td>إذا كان هناك نهار كان هناك نور، وبما أن هناك نهارا، إذن هناك نور</td></tr>\n<tr><td>إذا الأوّل الثاني، بما أنّ ليس الثاني، إذن ليس الأوّل</td><td>إذا كان هناك نهار كان هناك نور، بما أنه ليس هناك نور إذن ليس هناك نهار</td></tr>\n<tr><td>ليس الأوّل والثاني معا، بما أن الأوّل إذن ليس الثاني</td><td>غير صحيح أن يكون أفلاطون حيّا وميّتا، بما أن أفلاطون حيّ، إذن أفلاطون ليس ميّتا</td></tr>\n<tr><td>إمّا الأوّل وإمّا الثاني، بما أن الأوّل إذن ليس الثاني</td><td>إمّا هناك نهار وإمّا هناك ليل، بما أن هناك نهارا إذن ليس هناك ليل</td></tr>\n<tr><td>إمّا الأوّل وإمّا الثاني، بما أنّ ليس الثاني، إذن الأوّل</td><td>إمّا هناك نهار وإمّا هناك ليل، بما أن ليس هناك ليل، إذن هناك نهار</td></tr>\n</table>"
            },
            "fr": {
                "name": "Logique Stoïcienne",
                "first_letter": "L",
                "name_and_origin": "Logique d'origine mégarique, née au sein de l'école philosophique stoïcienne. Contrairement à la logique aristotélicienne qui correspondait à une philosophie de la matière et de la substance (logique du concept), la logique stoïcienne se réfère à une philosophie nominaliste qui considère qu'il n'existe ni espèces ni substances, mais seulement des êtres et des faits individuels.",
                "pioneers_and_reference_texts": "Zénon de Citium (264-335 av. J.-C.), fondateur du stoïcisme, et Chrysippe (280-204 av. J.-C.) qui a développé la logique stoïcienne de manière systématique. En raison de la perte de la plupart des textes originaux, notre connaissance de la logique stoïcienne provient de sources ultérieures telles que les écrits de Sextus Empiricus, Galien, et certains philosophes chrétiens.",
                "central_thesis_and_key_concepts": "Les propositions logiques expriment selon eux des faits qui se produisent dans le temps ou des relations entre faits. Ils distinguent les propositions simples des propositions composées, ces dernières se répartissant en six types : 1) proposition conditionnelle 2) proposition consécutive ou inférentielle 3) proposition conjonctive 4) proposition disjonctive 5) proposition causale 6) proposition comparative (augmentative et diminutive).",
                "method_and_domain": "Le raisonnement se compose d'une majeure, d'une mineure et d'une conclusion. Les stoïciens ont utilisé la métonymie dans la formulation des formes de raisonnement. Chrysippe a proposé cinq méthodes d'organisation du raisonnement basées sur des formes déductives spécifiques.",
                "relations_and_critique": "Relation étroite avec la logique mégarique et divergence radicale avec la logique aristotélicienne concernant la nature des propositions et du raisonnement. La logique stoïcienne a été critiquée par les péripatéticiens qui préféraient la logique aristotélicienne, mais elle a ensuite influencé le développement de la logique propositionnelle.",
                "impact_and_applications": "La logique stoïcienne est considérée comme la première formulation systématique de la logique propositionnelle dans l'histoire de la pensée occidentale. Elle constituait une partie essentielle de la philosophie stoïcienne aux côtés de la physique et de l'éthique. Elle a influencé le développement de la logique au Moyen Âge et certains aspects de la logique moderne.",
                "equivalent_terms": "Logique stoïcienne, logique des stoïciens, logique propositionnelle stoïcienne",
                "other": "Les stoïciens considèrent que du vrai on peut déduire le vrai et du faux on peut déduire le faux, et que le vrai peut découler du faux mais que le faux ne peut pas être déduit du vrai. Le tableau suivant illustre les types de propositions composées chez les stoïciens:\n\n<table>\n<tr><th colspan='2'>Type de proposition</th><th>Exemple</th></tr>\n<tr><td colspan='2'>Proposition conditionnelle</td><td>S'il fait jour, il y a de la lumière</td></tr>\n<tr><td>Proposition consécutive ou inférentielle</td><td>Proposition consécutive ou inférentielle</td><td>Puisqu'il fait jour, il y a de la lumière</td></tr>\n<tr><td>Proposition conjonctive</td><td>Proposition conjonctive</td><td>Il fait jour et il y a de la lumière</td></tr>\n<tr><td>Proposition disjonctive</td><td>Proposition disjonctive</td><td>Soit il fait jour, soit il y a de la lumière</td></tr>\n<tr><td>Proposition causale</td><td>Proposition causale</td><td>Parce qu'il fait jour, il y a de la lumière</td></tr>\n<tr><td colspan='2'>Proposition comparative augmentative</td><td>Il y a plus de jour que de nuit</td></tr>\n<tr><td colspan='2'>Proposition comparative diminutive</td><td>Il y a moins de nuit que de jour</td></tr>\n</table>\n\nEt voici les cinq formes de raisonnement selon Chrysippe:\n\n<table>\n<tr><th>Forme de raisonnement</th><th>Exemple</th></tr>\n<tr><td>Si le premier, alors le second; or le premier; donc le second</td><td>S'il fait jour, il y a de la lumière; or il fait jour; donc il y a de la lumière</td></tr>\n<tr><td>Si le premier, alors le second; or non le second; donc non le premier</td><td>S'il fait jour, il y a de la lumière; or il n'y a pas de lumière; donc il ne fait pas jour</td></tr>\n<tr><td>Non (le premier et le second); or le premier; donc non le second</td><td>Il n'est pas vrai que Platon soit vivant et mort; or Platon est vivant; donc Platon n'est pas mort</td></tr>\n<tr><td>Soit le premier, soit le second; or le premier; donc non le second</td><td>Soit il fait jour, soit il fait nuit; or il fait jour; donc il ne fait pas nuit</td></tr>\n<tr><td>Soit le premier, soit le second; or non le second; donc le premier</td><td>Soit il fait jour, soit il fait nuit; or il ne fait pas nuit; donc il fait jour</td></tr>\n</table>"
            },
            "en": {
                "name": "Stoic Logic",
                "first_letter": "S",
                "name_and_origin": "A logic of Megarian origins, born within the Stoic philosophical school. Unlike Aristotelian logic which corresponded to a philosophy of matter and substance (logic of the concept), Stoic logic refers to a nominalist philosophy that considers there to be no species or substances, but only beings and individual facts.",
                "pioneers_and_reference_texts": "Zeno of Citium (264-335 BC), founder of Stoicism, and Chrysippus (280-204 BC) who developed Stoic logic systematically. Due to the loss of most original texts, our knowledge of Stoic logic comes from later sources such as the writings of Sextus Empiricus, Galen, and some Christian philosophers.",
                "central_thesis_and_key_concepts": "Logical propositions in their view express facts that occur in time or relations between facts. They distinguish between simple and compound propositions, with compound propositions divided into six types: 1) conditional proposition 2) consecutive or inferential proposition 3) conjunctive proposition 4) disjunctive proposition 5) causal proposition 6) comparative proposition (augmentative and diminutive).",
                "method_and_domain": "Reasoning consists of a major premise, a minor premise, and a conclusion. The Stoics used metonymy in formulating reasoning forms. Chrysippus proposed five methods of organizing reasoning based on specific deductive forms.",
                "relations_and_critique": "Close relationship with Megarian logic and radical divergence from Aristotelian logic regarding the nature of propositions and reasoning. Stoic logic was criticized by Peripatetics who preferred Aristotelian logic, but it later influenced the development of propositional logic.",
                "impact_and_applications": "Stoic logic is considered the first systematic formulation of propositional logic in the history of Western thought. It formed an essential part of Stoic philosophy alongside physics and ethics. It influenced the development of logic in the Middle Ages and some aspects of modern logic.",
                "equivalent_terms": "Stoic logic, logic of the Stoics, Stoic propositional logic",
                "other": "The Stoics considered that from truth one can deduce truth and from falsehood one can deduce falsehood, and that truth can result from falsehood but falsehood cannot be deduced from truth. The following table illustrates the types of compound propositions in Stoicism:\n\n<table>\n<tr><th colspan='2'>Type of Proposition</th><th>Example</th></tr>\n<tr><td colspan='2'>Conditional proposition</td><td>If it is day, there is light</td></tr>\n<tr><td>Consecutive or inferential proposition</td><td>Consecutive or inferential proposition</td><td>Since it is day, there is light</td></tr>\n<tr><td>Conjunctive proposition</td><td>Conjunctive proposition</td><td>It is day and there is light</td></tr>\n<tr><td>Disjunctive proposition</td><td>Disjunctive proposition</td><td>Either it is day or there is light</td></tr>\n<tr><td>Causal proposition</td><td>Causal proposition</td><td>Because it is day, there is light</td></tr>\n<tr><td colspan='2'>Augmentative comparative proposition</td><td>There is more day than night</td></tr>\n<tr><td colspan='2'>Diminutive comparative proposition</td><td>There is less night than day</td></tr>\n</table>\n\nAnd here are the five forms of reasoning according to Chrysippus:\n\n<table>\n<tr><th>Form of Reasoning</th><th>Example</th></tr>\n<tr><td>If the first, then the second; but the first; therefore the second</td><td>If it is day, there is light; but it is day; therefore there is light</td></tr>\n<tr><td>If the first, then the second; but not the second; therefore not the first</td><td>If it is day, there is light; but there is no light; therefore it is not day</td></tr>\n<tr><td>Not (the first and the second); but the first; therefore not the second</td><td>It is not true that Plato is alive and dead; but Plato is alive; therefore Plato is not dead</td></tr>\n<tr><td>Either the first or the second; but the first; therefore not the second</td><td>Either it is day or it is night; but it is day; therefore it is not night</td></tr>\n<tr><td>Either the first or the second; but not the second; therefore the first</td><td>Either it is day or it is night; but it is not night; therefore it is day</td></tr>\n</table>"
            }
        },
		        {
            "id": "school4",
            "ar": {
                "name": "منطق بور رويال",
                "first_letter": "م",
                "name_and_origin": "هو المنطق الوارد في كتاب \"المنطق أو فن التفكير\" (La Logique ou l'Art de penser) الصادر سنة 1662 دون اسم مؤلف والمنسوب إلى أنطوان أرنو وبيار نيكول. يُعرف هذا المنطق أيضًا باسم \"المنطق الأرنولدي\" نسبةً إلى أنطوان أرنو.",
                "pioneers_and_reference_texts": "أنطوان أرنو، بيار نيكول. النص المرجعي الأساسي: \"المنطق أو فن التفكير\" (La Logique ou l'Art de penser) الصادر عام 1662.",
                "central_thesis_and_key_concepts": "لا يرى هؤلاء المناطقة في المنطق علماً نتعلّم بواسطته تركيب الكلمات أو الصيغ بل فناً نتعلّم بواسطته التفكير على الوجه الأفضل. إنه فنّ لتكوين الحكم وليس تعليماً لوصايا، كما أنّه أقرب إلى الممارسة منه إلى الشأن النظري. لا يرمي هذا المنطق إلى إعفاء عقلنا من التفكير عبر تطبيق شبه آلي لوصايا، بل إلى تمرينه على التفكير الجيّد.",
                "method_and_domain": "اتجه هؤلاء المناطقة إلى توسيع مجال المنطق لجعله في متناول العلوم الأخرى وفي متناول الإنسان في مختلف ظروف حياته التي تستوجب استعمالاً للعقل، لذلك جاء الكتاب دائم الاعتماد على الأمثلة بهدف التشجيع على تطبيق المنطق. تتمثل الإضافة النظرية الأساسية لمنطق بور رويال في الجمع بين التحليل المنطقي والتحليل النحوي للقضايا، فمعظم تحليلاتهم للغة ترمي إلى إظهار الأشكال المنطقية الأساسية التي غالباً ما تتخفّى وراء أشكال العبارة المتنوّعة.",
                "relations_and_critique": "يستند هذا المنطق إلى التقليد الديكارتي في التأكيد على وضوح الأفكار ودقّتها، كما يتأثر بالفلسفة الأغسطينية. تعرّض للنقد من قبل بعض الفلاسفة الذين رأوا في خلطه بين المنطق والنحو إشكالية منهجية، ومن قبل آخرين الذين اعتبروا أن تركيزه على الجانب العملي والتطبيقي قد أضعف البناء النظري للمنطق.",
                "impact_and_applications": "ساهم منطق بور رويال في تعميم المنطق وجعله أداة مفيدة للعلوم الأخرى وللحياة العملية. أثّر على تطوير المنطق التعليمي والتربوي في القرون اللاحقة، كما مهّد الطريق لدراسات لاحقة في فلسفة اللغة والتحليل النحوي-المنطقي.",
                "equivalent_terms": "المنطق الأرنولدي، منطق بورت رويال، فن التفكير",
                "other": "يُعتبر كتاب \"المنطق أو فن التفكير\" واحداً من أكثر الكتب تأثيراً في المنطق خلال العصر الحديث المبكر، وقد استُخدم ككتاب مدرسي في العديد من المؤسسات التعليمية الأوروبية لقرون."
            },
            "fr": {
                "name": "Logique de Port-Royal",
                "first_letter": "L",
                "name_and_origin": "Il s'agit de la logique présentée dans le livre \"La Logique ou l'Art de penser\" publié en 1662 sans nom d'auteur et attribué à Antoine Arnauld et Pierre Nicole. Cette logique est également connue sous le nom de \"logique arnaldienne\" en référence à Antoine Arnauld.",
                "pioneers_and_reference_texts": "Antoine Arnauld, Pierre Nicole. Texte de référence principal : \"La Logique ou l'Art de penser\" publié en 1662.",
                "central_thesis_and_key_concepts": "Ces logiciens ne voient pas dans la logique une science par laquelle nous apprenons à composer des mots ou des formules, mais un art par lequel nous apprenons à penser de la meilleure façon. C'est un art de former le jugement et non un enseignement de préceptes, et il est plus proche de la pratique que de la théorie. Cette logique ne vise pas à dispenser notre esprit de penser par l'application quasi automatique de préceptes, mais à l'entraîner à bien penser.",
                "method_and_domain": "Ces logiciens ont cherché à élargir le champ de la logique pour la rendre accessible aux autres sciences et à l'homme dans les diverses circonstances de sa vie qui nécessitent l'usage de la raison. C'est pourquoi le livre s'appuie constamment sur des exemples pour encourager l'application de la logique. L'apport théorique fondamental de la logique de Port-Royal réside dans la combinaison de l'analyse logique et de l'analyse grammaticale des propositions, la plupart de leurs analyses du langage visant à révéler les formes logiques fondamentales souvent cachées derrière la diversité des expressions.",
                "relations_and_critique": "Cette logique s'appuie sur la tradition cartésienne en insistant sur la clarté et la précision des idées, et est influencée par la philosophie augustinienne. Elle a été critiquée par certains philosophes qui ont vu dans son mélange de logique et de grammaire un problème méthodologique, et par d'autres qui ont considéré que son accent sur l'aspect pratique et appliqué avait affaibli l'édifice théorique de la logique.",
                "impact_and_applications": "La logique de Port-Royal a contribué à populariser la logique et à en faire un outil utile pour les autres sciences et pour la vie pratique. Elle a influencé le développement de la logique éducative et pédagogique dans les siècles suivants, et a ouvert la voie à des études ultérieures en philosophie du langage et en analyse grammatico-logique.",
                "equivalent_terms": "Logique arnaldienne, logique de Port-Royal, art de penser",
                "other": "Le livre \"La Logique ou l'Art de penser\" est considéré comme l'un des ouvrages les plus influents en logique au début de l'époque moderne, et a été utilisé comme manuel dans de nombreuses institutions éducatives européennes pendant des siècles."
            },
            "en": {
                "name": "Port-Royal Logic",
                "first_letter": "P",
                "name_and_origin": "This is the logic presented in the book \"La Logique ou l'Art de penser\" (Logic or the Art of Thinking) published in 1662 without an author's name and attributed to Antoine Arnauld and Pierre Nicole. This logic is also known as \"Arnauldian logic\" in reference to Antoine Arnauld.",
                "pioneers_and_reference_texts": "Antoine Arnauld, Pierre Nicole. Main reference text: \"La Logique ou l'Art de penser\" published in 1662.",
                "central_thesis_and_key_concepts": "These logicians do not see logic as a science by which we learn to compose words or formulas, but as an art by which we learn to think in the best way. It is an art of forming judgment and not a teaching of precepts, and it is closer to practice than to theory. This logic does not aim to relieve our mind from thinking through the quasi-automatic application of precepts, but to train it to think well.",
                "method_and_domain": "These logicians sought to expand the field of logic to make it accessible to other sciences and to humans in various circumstances of life that require the use of reason. That is why the book constantly relies on examples to encourage the application of logic. The fundamental theoretical contribution of Port-Royal logic lies in the combination of logical analysis and grammatical analysis of propositions, with most of their language analyses aiming to reveal the fundamental logical forms often hidden behind diverse expressions.",
                "relations_and_critique": "This logic is based on the Cartesian tradition in emphasizing clarity and precision of ideas, and is influenced by Augustinian philosophy. It has been criticized by some philosophers who saw in its mixture of logic and grammar a methodological problem, and by others who considered that its emphasis on the practical and applied aspect had weakened the theoretical edifice of logic.",
                "impact_and_applications": "Port-Royal logic contributed to popularizing logic and making it a useful tool for other sciences and for practical life. It influenced the development of educational and pedagogical logic in subsequent centuries, and paved the way for later studies in philosophy of language and grammatical-logical analysis.",
                "equivalent_terms": "Arnauldian logic, Port-Royal logic, Art of Thinking",
                "other": "The book \"La Logique ou l'Art de penser\" is considered one of the most influential works in logic during the early modern period, and was used as a textbook in many European educational institutions for centuries."
            }
        },
		{
    "id": "school5",
    "ar": {
        "name": "الوضعيّة المنطقيّة",
        "first_letter": "و",
        "name_and_origin": "تُحيل هذه التسمية على الأطروحات التي عُرِفت بها مجموعة من المفكرين عملوا في فيينا خلال العشرينات من القرن العشرين، منتسبين إلى ما أصبح يعرف 'بحلقة فيينا' (Cercle de Vienne). وقد تأثّر هؤلاء جميعا بأطروحات فيغنشتاين (Wittgenstein) في كتابه 'الرّسالة المنطقيّة الفلسفية' (Tractatus logico-philosophicus).",
        "pioneers_and_reference_texts": "كارناب (Carnap)، نوراث (Neurath)، وايزمان (Waisman)، هان (Hann)، شليك (Schlick). من النصوص المرجعية: 'الرسالة المنطقية الفلسفية' (فيغنشتاين)، 'البناء المنطقي للعالم' (كارناب)، 'مقالات علمية موحدة' (أعمال حلقة فيينا).",
        "central_thesis_and_key_concepts": "لا يتمثل هدف الفلسفة في إنتاج معرفة، بل في توضيح دلالة القضايا، أي في تحليل اللغة بغرض التمييز بين قضايا مشروعة من وجهة معرفية وقضايا غير مشروعة. هناك نوعان من القضايا التي لها معنى: الملفوظات التحليلية (قضايا المنطق والرياضيات) وهي قضايا ما قبلية لا تزعم الإعلام بشيء عن الواقع، والملفوظات التأليفية (القضايا العلمية) التي تُتحقّق بالرجوع إلى التجربة. القضايا الميتافيزيقية تُعتبر بلا معنى (أشباه قضايا). مبدأ التحقق (Verification Principle) هو حجر الزاوية في تحديد المعنى.",
        "method_and_domain": "التحليل المنطقي للغة، وتوضيح شروط الدلالة المعرفية. تطبيق مبدأ التحقق التجريبي لتحديد القضايا ذات المعنى. التركيز على فلسفة العلوم والمنطق واللغة.",
        "relations_and_critique": "تأثرت بشدة بفيغنشتاين المبكر ومنطق فريجه وراسل. قطعت مع الميتافيزيقيا والفلسفة التقليدية. تعرضت لانتقادات قوية فيما بعد، خاصة من كواين (Quine) الذي هاجم التمييز التحليلي/التأليفي، ومن كارل بوبر (Popper) الذي طرح مبدأ التكذيب (Falsification) بديلاً عن التحقق، ومن النقاد الذين رأوا في منهجها اختزالاً وتضييقًا مفرطًا لمجال الفلسفة والمعنى.",
        "impact_and_applications": "كان لها تأثير عميق على فلسفة العلم في القرن العشرين، وساهمت في تطوير الفلسفة التحليلية. رفعت من شأن الدقة المنطقية واللغة العلمية، وأسست لما يُعرف بـ 'وحدة العلوم' تحت لواء اللغة الفيزيائية. أثرت على مجالات السيمانتيك (علم الدلالة) والابستمولوجيا المعاصرة.",
        "equivalent_terms": "الوضعية الجديدة، التجريبية المنطقية، حلقة فيينا",
        "other": "تعتبر الوضعية المنطقية واحدة من أهم الحركات الفلسفية في القرن العشرين التي سعت لجعل الفلسفة علمية ودقيقة، رغم أن العديد من أطروحاتها الأساسية (مثل مبدأ التحقق الصارم) وُجهت إليها انتقادات أدت إلى تطورات لاحقة وتعديلات داخل الفلسفة التحليلية نفسها."
    },
    "fr": {
        "name": "Positivisme Logique",
        "first_letter": "P",
        "name_and_origin": "Cette désignation fait référence aux thèses défendues par un groupe de penseurs qui ont travaillé à Vienne dans les années 1920, affiliés à ce qui est devenu le 'Cercle de Vienne'. Ils ont tous été influencés par les thèses de Wittgenstein dans son ouvrage 'Tractatus logico-philosophicus'.",
        "pioneers_and_reference_texts": "Carnap, Neurath, Waisman, Hann, Schlick. Textes de référence : 'Tractatus logico-philosophicus' (Wittgenstein), 'La Construction logique du monde' (Carnap), 'Le Manifeste du Cercle de Vienne' (Wissenschaftliche Weltauffassung).",
        "central_thesis_and_key_concepts": "Le but de la philosophie n'est pas de produire des connaissances, mais de clarifier la signification des propositions, c'est-à-dire d'analyser le langage afin de distinguer les propositions légitimes d'un point de vue cognitif des propositions illégitimes. Il existe deux types de propositions significatives : les énoncés analytiques (propositions de logique et de mathématiques) qui sont a priori et ne prétendent rien informer sur la réalité, et les énoncés synthétiques (propositions scientifiques) qui sont vérifiées par référence à l'expérience. Les propositions métaphysiques sont considérées comme dénuées de sens (pseudo-propositions). Le principe de vérification (Verification Principle) est la pierre angulaire pour déterminer la signification.",
        "method_and_domain": "Analyse logique du langage et clarification des conditions de la signification cognitive. Application du principe de vérification empirique pour identifier les propositions significatives. Focus sur la philosophie des sciences, la logique et le langage.",
        "relations_and_critique": "Fortement influencé par le premier Wittgenstein, la logique de Frege et Russell. Rupture avec la métaphysique et la philosophie traditionnelle. A ensuite été vivement critiqué, notamment par Quine qui a attaqué la distinction analytique/synthétique, par Karl Popper qui a proposé le principe de falsification comme alternative à la vérification, et par des critiques qui y ont vu une réduction excessive du domaine de la philosophie et du sens.",
        "impact_and_applications": "A eu une influence profonde sur la philosophie des sciences au XXe siècle et a contribué au développement de la philosophie analytique. A mis en valeur la précision logique et le langage scientifique, et a fondé l'idée de 'l'unité de la science' sous l'égide du langage physique. A influencé la sémantique et l'épistémologie contemporaines.",
        "equivalent_terms": "Néo-positivisme, Empirisme logique, Cercle de Vienne",
        "other": "Le positivisme logique est considéré comme l'un des mouvements philosophiques les plus importants du XXe siècle ayant cherché à rendre la philosophie scientifique et rigoureuse, bien que bon nombre de ses thèses fondamentales (comme le principe de vérification strict) aient été critiquées, conduisant à des développements et ajustements ultérieurs au sein même de la philosophie analytique."
    },
    "en": {
        "name": "Logical Positivism",
        "first_letter": "L",
        "name_and_origin": "This designation refers to the theses defended by a group of thinkers who worked in Vienna in the 1920s, affiliated with what became known as the 'Vienna Circle'. They were all influenced by Wittgenstein's theses in his work 'Tractatus Logico-Philosophicus'.",
        "pioneers_and_reference_texts": "Carnap, Neurath, Waisman, Hann, Schlick. Reference texts: 'Tractatus Logico-Philosophicus' (Wittgenstein), 'The Logical Structure of the World' (Carnap), 'The Scientific Conception of the World: The Vienna Circle' (manifesto).",
        "central_thesis_and_key_concepts": "The aim of philosophy is not to produce knowledge, but to clarify the meaning of propositions, i.e., to analyze language in order to distinguish between propositions that are legitimate from a cognitive standpoint and those that are not. There are two types of meaningful propositions: analytic statements (logical and mathematical propositions) which are a priori and claim to inform nothing about reality, and synthetic statements (scientific propositions) which are verified by reference to experience. Metaphysical propositions are considered meaningless (pseudo-propositions). The Verification Principle is the cornerstone for determining meaning.",
        "method_and_domain": "Logical analysis of language and clarification of the conditions for cognitive significance. Application of the empirical verification principle to identify meaningful propositions. Focus on philosophy of science, logic, and language.",
        "relations_and_critique": "Heavily influenced by early Wittgenstein, Frege's and Russell's logic. Broke with metaphysics and traditional philosophy. Later faced strong criticisms, particularly from Quine who attacked the analytic/synthetic distinction, from Karl Popper who proposed the falsification principle as an alternative to verification, and from critics who saw in it an excessive reduction and narrowing of the domain of philosophy and meaning.",
        "impact_and_applications": "Had a profound influence on the philosophy of science in the 20th century and contributed to the development of analytic philosophy. Elevated the importance of logical precision and scientific language, and founded the idea of the 'unity of science' under the banner of physicalist language. Influenced contemporary semantics and epistemology.",
        "equivalent_terms": "Neo-Positivism, Logical Empiricism, Vienna Circle",
        "other": "Logical positivism is considered one of the most important philosophical movements of the 20th century that sought to make philosophy scientific and rigorous, although many of its fundamental theses (such as the strict verification principle) were criticized, leading to later developments and adjustments within analytic philosophy itself."
    }
},
{
    "id": "school6",
    "ar": {
        "name": "المنطق الأرسطي",
        "first_letter": "م",
        "name_and_origin": "المنطق الأرسطي هو النظام المنطقي الذي وضعه أرسطو (384–322 ق.م) وتطور على يد تلاميذه والمشائين. يُعتبر أول نظام منهجي للمنطق في تاريخ الفلسفة الغربية، وقد سُمي أيضًا بـ\"المنطق الصوري\" أو \"المنطق التقليدي\". يركز على تحليل أشكال الاستدلال الصحيحة بناءً على بنية القضايا وعلاقاتها.",
        "pioneers_and_reference_texts": "أرسطو، ثيوفراستوس، أفلاطون (كمؤثر). النصوص المرجعية الأساسية: \"الأورغانون\" (مجموعة مؤلفات أرسطو المنطقية)، خاصة \"المقولات\"، \"العبارة\"، \"التحليلات الأولى\"، \"التحليلات الثانية\"، \"الجدل\"، \"المغالطات\".",
        "central_thesis_and_key_concepts": "يرتكز المنطق الأرسطي على نظرية القياس (Syllogism)، حيث يتم الاستدلال من مقدمتين إلى نتيجة. مفاهيم رئيسية: المقولات العشر، القضية (حمليّة، موجبة/سالبة، كلية/جزئية)، الحد الأوسط، القياس (الكامل والناقص)، البرهان، الجدل، المغالطات.",
        "method_and_domain": "يستخدم المنطق الأرسطي منهجًا صوريًا تحليليًا لفحص صحة الاستدلالات. مجاله الرئيسي هو الاستدلال الاستنباطي، ويهتم بتصنيف المعرفة وطرق الحصول عليها (برهان، جدل، خطابة).",
        "relations_and_critique": "تأثر بالفلسفة الأفلاطونية ولكنه تميز بالتركيز على التحليل المنطقي للغة الطبيعية والعالم الطبيعي. تعرض لانتقادات من قبل المنطق الرواقي (الذي ركز على المنطق القضيوي)، ومن المنطق الحديث (خاصة فريجه وراسل) الذي اعتبره محدودًا في تعامله مع العلاقات والكميات.",
        "impact_and_applications": "سيطر المنطق الأرسطي على الفكر الغربي والعربي الإسلامي لأكثر من ألفي عام. كان أساس التعليم في التريفيوم (Trivium) في العصور الوسطى. لا يزال يُدرس كمدخل تاريخي للمنطق الصوري، وأثّر على تطور المنطق الرمزي الحديث.",
        "equivalent_terms": "المنطق الصوري، المنطق التقليدي، منطق أرسطو",
        "other": "قسّم أرسطو المعرفة إلى ثلاث درجات حسب درجة اليقين: البرهان (اليقيني)، الجدل (الاحتمالي)، الخطابة (المقنع). كما ميّز بين الضروري والممكن والواقعي في أنواع القضايا."
    },
    "fr": {
        "name": "Logique Aristotélicienne",
        "first_letter": "L",
        "name_and_origin": "La logique aristotélicienne est le système logique élaboré par Aristote (384–322 av. J.-C.) et développé par ses disciples et les péripatéticiens. Considérée comme le premier système systématique de logique dans l'histoire de la philosophie occidentale, elle est également appelée \"logique formelle\" ou \"logique traditionnelle\". Elle se concentre sur l'analyse des formes de raisonnement valides basées sur la structure des propositions et leurs relations.",
        "pioneers_and_reference_texts": "Aristote, Théophraste, Platon (comme influence). Textes de référence principaux : \"L'Organon\" (collection des œuvres logiques d'Aristote), en particulier \"Les Catégories\", \"De l'interprétation\", \"Premiers Analytiques\", \"Seconds Analytiques\", \"Les Topiques\", \"Les Réfutations sophistiques\".",
        "central_thesis_and_key_concepts": "La logique aristotélicienne repose sur la théorie du syllogisme, où l'on déduit une conclusion à partir de deux prémisses. Concepts clés : les dix catégories, la proposition (catégorique, affirmative/négative, universelle/particulière), le terme moyen, le syllogisme (parfait et imparfait), la démonstration, la dialectique, les sophismes.",
        "method_and_domain": "La logique aristotélicienne utilise une méthode formelle et analytique pour examiner la validité des raisonnements. Son domaine principal est le raisonnement déductif, et elle s'intéresse à la classification de la connaissance et aux méthodes pour l'acquérir (démonstration, dialectique, rhétorique).",
        "relations_and_critique": "Influencée par la philosophie platonicienne, elle se distingue par son accent sur l'analyse logique du langage naturel et du monde naturel. Elle a été critiquée par la logique stoïcienne (axée sur la logique propositionnelle) et par la logique moderne (notamment Frege et Russell) qui l'ont considérée comme limitée dans son traitement des relations et des quantificateurs.",
        "impact_and_applications": "La logique aristotélicienne a dominé la pensée occidentale et arabo-islamique pendant plus de deux millénaires. Elle a été la base de l'enseignement dans le Trivium au Moyen Âge. Elle est encore enseignée comme introduction historique à la logique formelle et a influencé le développement de la logique symbolique moderne.",
        "equivalent_terms": "Logique formelle, logique traditionnelle, logique d'Aristote",
        "other": "Aristote a divisé la connaissance en trois degrés selon le niveau de certitude : la démonstration (certaine), la dialectique (probable), la rhétorique (persuasive). Il a également distingué le nécessaire, le possible et le réel dans les types de propositions."
    },
    "en": {
        "name": "Aristotelian Logic",
        "first_letter": "A",
        "name_and_origin": "Aristotelian logic is the logical system developed by Aristotle (384–322 BC) and expanded by his disciples and the Peripatetics. Considered the first systematic system of logic in the history of Western philosophy, it is also called \"formal logic\" or \"traditional logic\". It focuses on analyzing valid forms of reasoning based on the structure of propositions and their relationships.",
        "pioneers_and_reference_texts": "Aristotle, Theophrastus, Plato (as an influence). Main reference texts: \"The Organon\" (collection of Aristotle's logical works), especially \"Categories\", \"On Interpretation\", \"Prior Analytics\", \"Posterior Analytics\", \"Topics\", \"Sophistical Refutations\".",
        "central_thesis_and_key_concepts": "Aristotelian logic is based on the theory of the syllogism, where a conclusion is deduced from two premises. Key concepts: the ten categories, the proposition (categorical, affirmative/negative, universal/particular), the middle term, the syllogism (perfect and imperfect), demonstration, dialectic, fallacies.",
        "method_and_domain": "Aristotelian logic uses a formal and analytical method to examine the validity of arguments. Its main domain is deductive reasoning, and it is concerned with the classification of knowledge and methods for acquiring it (demonstration, dialectic, rhetoric).",
        "relations_and_critique": "Influenced by Platonic philosophy, it is distinguished by its focus on the logical analysis of natural language and the natural world. It was criticized by Stoic logic (focused on propositional logic) and by modern logic (especially Frege and Russell) who considered it limited in its treatment of relations and quantifiers.",
        "impact_and_applications": "Aristotelian logic dominated Western and Arab-Islamic thought for over two millennia. It was the basis of education in the Trivium during the Middle Ages. It is still taught as a historical introduction to formal logic and influenced the development of modern symbolic logic.",
        "equivalent_terms": "Formal logic, Traditional logic, Aristotle's logic",
        "other": "Aristotle divided knowledge into three degrees according to the level of certainty: demonstration (certain), dialectic (probable), rhetoric (persuasive). He also distinguished between necessary, possible, and actual in types of propositions."
    }
}
    ],
    "section_title": {
        "ar": "المدارس الفلسفية",
        "fr": "Écoles Philosophiques",
        "en": "Philosophical Schools"
    }
};
